# StatusPlugin made by Fynnyx

default:
  # Enable if the player should get always a default status when the player joins the server
  use-default-on-join: false
  #Set the default status. It will also be set if the player doesn't have a status set.
  default-status: 'afk'
# Define the statuses. The root Element is the selection in the command.
# The color is defined by the default minecraft colors.
statuses:
  AFK:
    prefix: AFK
    color: 8
  Chill:
    prefix: Chill
    color: a
#  Create a list of statuses. The root Element is the selection in the command.
#  For example ... an so on
# rp:
#   prefix: RP
#   color: b


# TABLIST
tablist:
  # Enable the tablist from this plugin. (PlaceholderAPI compatible)
  enabled: true

  # To color the text use the & symbol
  # You can use the following placeholders:
  # %username% - The username of the player
  # %status% - The status of the player
  format: "&7[%status% &r%username%&7]"

# CHAT
chat:
  # Enable the chat format from this plugin. (PlaceholderAPI compatible)
  enabled: true

  # To color the text use the & symbol
  # You can use the following placeholders:
  # %username% - The username of the player
  # %status% - The status of the player
  # %message% - display the message
  format: "&7[%status% &r%username%&7] &r%message%"

# JOIN/LEAVE MESSAGE
join-leave:
  # Enable the join message from this plugin. (PlaceholderAPI compatible)
  enabled: true

  # To color the text use the & symbol
  # You can use the following placeholders:
  # %username% - The username of the player
  # %status% - The status of the player
  join-message-format: "&7[%status% &r%username%&7] &ejoined the server"
  leave-message-format: "&7[%status% &r%username%&7] &eleft the server"

# AFK
afk:
  # Enable the AFK status
  enabled: true
  # Set the AFK status. It must be defined in the statuses section.
  status: 'AFK'
  # Set the time in seconds after the player is marked as AFK
  time: 300


# PlaceholderAPI Support
placeholders:
  status:
    placeholderString: '%status%'
    returnWithColorFormatting: true
