name: Statusplugin
version: '${project.version}'
main: ch.fynnyx.statusplugin.Statusplugin
api-version: 1.21
authors: [ Fynnyx ] 
description: Define Statuses and display them in the Tab and in the Chat.
depend:
  - LuckPerms
softdepend:
  - PlaceholderAPI
  
commands:
  status:
    description: "Set your status!"
    usage: /status <status>
    aliases:
      - st
    permission: status.setstatus
  reloadstatus:
    description: "Reload the config!"
    usage: /reloadstatus
    permission: status.reload

permissions:
  status.setstatus:
    description: "Set your status!"
    default: true
  status.setother:
    description: "Set other players status!"
    default: false
  status.reload:
    description: "Reload the config!"
    default: op